spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
        format_sql: true

    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true # debug