server:
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/college?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: create-drop
  security:
    jwt:
      secret-key: JoFjCo0sceo5JLRj2EeEQ7GvkWM9wzTBcrw9hkRipL6LxVr7jESfuwcKWHw3ZZHj
      expiration: 604800000 # 7 days in millis